apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: sample
  namespace: openshift-gitops
spec:
  generators:
  - clusterDecisionResource:
      configMapRef: acm-placement
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/placement: sample
      requeueAfterSeconds: 180
  - list:
      elements:
      - cluster: engineering-dev
        url: https://kubernetes.default.svc
      - cluster: engineering-prod
        url: https://kubernetes.default.svc
      - template: sample
  template:
    metadata:
      annotations:
        app.kubernetes.io/instance: '{{name}}'
        argocd.argoproj.io/compare-options: IgnoreExtraneous
      labels:
        velero.io/exclude-from-backup: "true"
        url: "{{url}}"
        cluster: "{{cluster}}"
      name: "{{name}}"
      namespace: openshift-gitops
    spec:
      destination:
        namespace: openshift-gitops
        server: '{{server}}'
      project: default
    # in ocp 4.14 multiple sources can be added ( see gitlab operator appset)
    # Due to this u cant see app details link in ACM UI
      source:
        helm:
          releaseName: cm-sample
          valueFiles:
          - values.yaml
        path: charts/sample
        repoURL: https://github.com/ajaykanse/acm.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - PruneLast=true
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: sample
  namespace: openshift-gitops
spec:
  clusterSets:
  - production


