apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cert-utils-operator
  namespace: cert-utils-operator
spec:
  channel: alpha
  installPlanApproval: {{ .Values.approval }}
  name: cert-utils-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: cert-utils-operator.{{ .Values.version }}